- name: DOwnload tar file from tomcat website
  get_url: url=http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.24/bin/apache-tomcat-8.5.24.tar.gz dest=/opt/tomcat.tar.gz

- name: Untar the downloaded file
  unarchive: src=/opt/tomcat.tar.gz dest=/opt/

- name: Rename Folder
  command: mv /opt/apache-tomcat-8.5.24 /opt/tomcat

- name: Copy init Script
  copy: src=init.sh dest=/etc/init.d/tomcat mode=0755

- name: Change Permission
  command: chmod -R 755 /opt/tomcat/bin

- name: Start Service
  service: name=tomcat state=restarted 
